server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7002.springcloud:7002/eureka,http://eureka7003.springcloud:7003/eureka  #集群版
  instance:
    instance-id: order80
    prefer-ip-address: true

